services:
  postgres:
    image: postgres:16
    container_name: vitallogix-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-vitallogix}
      POSTGRES_USER: ${POSTGRES_USER:-vitallogix}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - vitallogix_data:/var/lib/postgresql/data

  vitallogix-app: # <--- Cambié 'backend' por 'vitallogix-app'
    build: .
    container_name: vitallogix-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB:-vitallogix}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-vitallogix}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO:-update}
      - JWT_SECRET=${JWT_SECRET}
      - APP_BOOTSTRAP_ADMIN_USERNAME=${APP_BOOTSTRAP_ADMIN_USERNAME:-admin1}
      - APP_BOOTSTRAP_ADMIN_PASSWORD=${APP_BOOTSTRAP_ADMIN_PASSWORD}
      - APP_BOOTSTRAP_DEMO_USER_ENABLED=${APP_BOOTSTRAP_DEMO_USER_ENABLED:-true}
      - APP_BOOTSTRAP_DEMO_USER_USERNAME=${APP_BOOTSTRAP_DEMO_USER_USERNAME:-user1}
      - APP_BOOTSTRAP_DEMO_USER_PASSWORD=${APP_BOOTSTRAP_DEMO_USER_PASSWORD}

volumes:
  vitallogix_data: